.Dd January, 2012
.Os
.Dt dmnzr 8
.Sh NAME
.Nm dmnzr
.Nd daemonize a program
.Sh SYNOPSIS
.Nm
.Op Fl f logfile
.Ar executable
.Sh DESCRIPTION
.Bl -tag -width indent
.It Fl f Ar logfile
Log stdout and stderr of
.Ar executable
to
.Ar logfile
.SH BUG
As current working directory is never changed, the partition on which
.Ar executable
was launched will not be unmountable.
It thus allows not to worry about giving absolute
filenames to both
.Nm
and
.Ar executable
